[big]*i.     Abstract*

The ability to model, simulate and make predications about our  world can be advanced rapidly by bringing together several technologies.  This advancement can be accelerated based on the  concepts of geospatial information and the mechanisms of the Open Geospatial Consortium. This OGC Tech Note provides a roadmap to advancing this convergence resulting in technology advancements that will improve applications leading to benefits in several market domains.

[big]*ii.    Keywords*

The following are keywords to be used by search engines and document catalogues.

ogcdoc, OGC document,  <tags separated by commas>

[big]*iii.   Preface*

[NOTE]
====
OGC develops Technology Notes in order to advance priority trends identified in by OGC Technology Forecasting.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
====
[big]*iv.    Submitting organizations*

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

Organization name(s)

[big]*v.     Submitters*

All questions regarding this submission should be directed to the editor or the submitters:

Name  Affiliation
